In [1]:
###########################
# Pre-processing the data #
###########################


import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import pandas
import math
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error

files = ['miller_idle', 'sam_wild', 'layton_idle', 'miller_wild', 'val_idle', 'layton_wild', 'sam_idle', 'val_wild']  #filename in the folder 

/home/layton/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


ModuleNotFoundError: No module named 'tensorflow'

In [9]:

def preprocessing(filename):

    d = pd.read_csv(filename)   #read the CSV file
    # print (d)
    d_drop = d.drop("Sensor type", axis=1)   #drop the first column -- sensor type
    #print (d_drop)
    d_matrix = d_drop.as_matrix()   # Using pandas again to convert the revised table into a matrix
    #print (d_matrix)

    n_array = np.array(d_matrix) # now we use numpy to convert the pandas matrix into a Numpy array
    #print (n_array)
   
    #delete the last row if the revised row number is odd, otherwise cut last too rows
    n_array = n_array[:-1] if len(n_array) % 2 == 1 else n_array[:-2] 
    #print (n_conc)

    #Concatenate the EMG and Accerlaration rows for (nearly) the same time moments
    n_conc = np.concatenate((n_array[::2], n_array[1::2]), axis = 1)    
    #print (n_conc)

    n_del = np.delete(n_conc, [1, 2], axis = 1) #delete the second and third columns of each list in the matrix
    print (n_del)
    np.savetxt(filename + 'processed', n_del, delimiter=',', fmt = '%f')  #save the output into a file
    return n_del

In [7]:
for f in files:
    data = preprocessing(f)
    print(data.shape)

[[ 4.0720e+03  1.0445e+01 -3.2800e-01  2.2650e-01 -9.4900e-01  1.2424e+01]
 [ 4.0430e+03  2.6840e+01 -3.1600e-01  2.1480e-01 -9.3700e-01  2.7884e+01]
 [ 4.0420e+03  3.7573e+01 -3.3500e-01  2.2650e-01 -9.4500e-01  3.8594e+01]
 ...
 [ 4.0410e+03  2.7594e+04 -3.0800e-01  2.5000e-01 -9.3300e-01  2.7596e+04]
 [ 4.0570e+03  2.7605e+04 -3.2000e-01  2.5780e-01 -9.8400e-01  2.7606e+04]
 [ 4.0160e+03  2.7615e+04 -3.2400e-01  2.6170e-01 -9.4100e-01  2.7617e+04]]
(2651, 6)
[[ 3.32300e+03  1.20290e+01 -9.70000e-02 -8.50000e-02  9.37500e-01
   1.54460e+01]
 [ 3.60600e+03  2.57270e+01 -1.25000e-01 -1.01000e-01  9.33500e-01
   2.74040e+01]
 [ 3.87600e+03  3.82600e+01 -1.21000e-01 -7.80000e-02  9.06200e-01
   3.99180e+01]
 ...
 [ 7.75800e+03  2.36587e+05  9.76500e-01  2.14800e-01 -4.57000e-01
   2.36588e+05]
 [ 7.65500e+03  2.36598e+05  1.00000e+00  1.79600e-01 -5.15000e-01
   2.36599e+05]
 [ 7.63100e+03  2.36608e+05  1.02730e+00  1.87500e-01 -5.74000e-01
   2.36609e+05]]
(19524, 6)
[[ 6.4320e+03  1.04